# ----
# Site

title: Basic Jekyll Postcss
description: A basic jekyll default template powered with postcss
url: https://nabaroa.github.io/basic-jekyll-postcss/
google_analytics_key:
permalink: pretty

collections:
  posts:
    title: Documentation
    position: 1

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
